import { createUseStyles } from "react-jss";

import { Theme } from "src/styles/theme";

export const useListStyles = createUseStyles((theme: Theme) => ({
  background: {
    alignItems: "center",
    background: theme.palette.white,
    display: "flex",
    height: "100vh",
    justifyContent: "center",
    padding: [0, theme.spacing(1)],
    width: "100%",
  },
  button: {
    "&:hover": {
      background: theme.palette.grey.main,
    },
    "&:not(:first-of-type)": {
      marginTop: theme.spacing(1),
    },
    alignItems: "center",
    background: theme.palette.grey.light,
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    display: "flex",
    gap: theme.spacing(1),
    padding: theme.spacing(2),
    transition: theme.hoverTransition,
  },
  card: {
    maxWidth: 426,
    padding: theme.spacing(2),
    width: "100%",
  },
  closeButton: {
    "&:hover": {
      background: theme.palette.grey.main,
    },
    alignItems: "center",
    background: theme.palette.grey.light,
    border: 0,
    borderRadius: "50%",
    cursor: "pointer",
    display: "flex",
    height: theme.spacing(4),
    justifyContent: "center",
    padding: 0,
    position: "absolute",
    right: 0,
    transition: theme.hoverTransition,
    width: theme.spacing(4),
  },
  closeButtonIcon: {
    height: 16,
    width: 16,
  },
  header: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
    marginBottom: theme.spacing(2),
    padding: [theme.spacing(0.5), 0],
    position: "relative",
  },
  icon: {
    height: "24px",
    width: "24px",
  },
  list: {
    "&::-webkit-scrollbar": {
      width: "4px",
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: theme.palette.grey.main,
    },
    "&::-webkit-scrollbar-thumb:hover": {
      backgroundColor: theme.palette.grey.dark,
    },
    display: "flex",
    flexDirection: "column",
    maxHeight: 270,
    overflowY: "auto",
  },
}));

export const useListRedesignStyles = createUseStyles((theme: Theme) => ({
  background: {
    alignItems: "center",
    backdropFilter: "blur(12px)",
    background: "rgba(8, 17, 50, 0.5)",
    display: "flex",
    height: "100vh",
    justifyContent: "center",
    padding: `0 ${theme.spacing(2)}px`,
    width: "100%",
    [theme.breakpoints.downM]: {
      padding: `0 ${theme.spacing(1.5)}px`,
    },
  },
  button: {
    "&:hover:not(:disabled)": {
      background:
        "linear-gradient(135deg, rgba(65, 201, 171, 0.16) 0%, rgba(243, 205, 82, 0.1) 100%)",
      boxShadow: "inset 0 0 0 1.5px rgba(65, 201, 171, 0.5) !important",
      transform: "none !important",
    },
    alignItems: "center",
    background: "#F3F6F7",
    border: "none",
    borderRadius: 16,
    boxShadow: "inset 0 0 0 1px rgba(10, 11, 13, 0.04) !important",
    cursor: "pointer",
    display: "flex",
    flexShrink: 0,
    gap: theme.spacing(1.25),
    padding: `${theme.spacing(1.75)}px ${theme.spacing(2.25)}px`,
    textAlign: "left",
    transform: "none !important",
    transition: "background 160ms ease, box-shadow 160ms ease",
    width: "100%",
    [theme.breakpoints.downM]: {
      borderRadius: 12,
      gap: theme.spacing(1),
      padding: `${theme.spacing(1.25)}px ${theme.spacing(1.5)}px`,
    },
  },
  buttonLabel: {
    color: theme.palette.black,
    fontSize: 15,
    fontWeight: 400,
    letterSpacing: "-0.01em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    [theme.breakpoints.downM]: {
      fontSize: 13,
    },
  },
  card: {
    backgroundColor: theme.palette.white.mainRedesign || "#FFFFFF",
    border: "1px solid rgba(65, 201, 171, 0.2)",
    borderRadius: 28,
    boxShadow: "0 28px 64px rgba(8, 17, 50, 0.22), 0 8px 20px rgba(8, 17, 50, 0.08)",
    display: "flex",
    flexDirection: "column",
    maxHeight: "80vh",
    maxWidth: 420,
    minHeight: 0,
    overflow: "hidden",
    padding: theme.spacing(3),
    width: "100%",
    [theme.breakpoints.downM]: {
      borderRadius: 18,
      boxShadow: "0 18px 40px rgba(8, 17, 50, 0.2), 0 4px 12px rgba(8, 17, 50, 0.08)",
      maxHeight: "58dvh",
      maxWidth: 360,
      padding: theme.spacing(1.5),
    },
  },
  closeButton: {
    "&:hover:not(:disabled)": {
      background: "rgba(65, 201, 171, 0.14)",
      boxShadow: "none !important",
      transform: "none !important",
    },
    "&:hover:not(:disabled) path, &:hover:not(:disabled) rect": {
      fill: theme.palette.primary.dark,
    },
    alignItems: "center",
    background: "#F3F6F7",
    border: 0,
    borderRadius: "50%",
    bottom: 0,
    boxShadow: "none !important",
    cursor: "pointer",
    display: "flex",
    height: 40,
    justifyContent: "center",
    margin: "auto 0",
    padding: 0,
    position: "absolute",
    right: 0,
    top: 0,
    transform: "none !important",
    transition: "background 160ms ease",
    width: 40,
    [theme.breakpoints.downM]: {
      height: 34,
      width: 34,
    },
  },
  closeButtonIcon: {
    display: "block",
    height: 14,
    width: 14,
  },
  header: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    justifyContent: "center",
    marginBottom: theme.spacing(2.5),
    minHeight: 44,
    padding: `${theme.spacing(0.5)}px 0`,
    position: "relative",
    [theme.breakpoints.downM]: {
      marginBottom: theme.spacing(1.25),
      minHeight: 38,
    },
  },
  icon: {
    flexShrink: 0,
    height: 28,
    width: 28,
    [theme.breakpoints.downM]: {
      height: 24,
      width: 24,
    },
  },
  list: {
    "&::-webkit-scrollbar": {
      width: 4,
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "rgba(10, 11, 13, 0.18)",
      borderRadius: 999,
    },
    "&::-webkit-scrollbar-thumb:hover": {
      backgroundColor: "rgba(10, 11, 13, 0.32)",
    },
    "&::-webkit-scrollbar-track": {
      backgroundColor: "transparent",
    },
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(1.25),
    maxHeight: 320,
    minHeight: 0,
    overflowX: "hidden",
    overflowY: "auto",
    padding: "2px 2px 4px 0",
    [theme.breakpoints.downM]: {
      gap: theme.spacing(1),
      maxHeight: "40dvh",
    },
  },
  title: {
    color: theme.palette.black,
    fontSize: 22,
    fontWeight: 700,
    letterSpacing: "-0.02em",
    [theme.breakpoints.downM]: {
      fontSize: 18,
    },
  },
}));
