import { createUseStyles } from "react-jss";

import { Theme } from "src/styles/theme";

export const useTokenListStyles = createUseStyles((theme: Theme) => ({
  addTokenButton: {
    "&:hover": {
      background: theme.palette.grey.main,
    },
    background: theme.palette.white,
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    minWidth: 120,
    padding: 8,
    position: "absolute",
    right: 10,
    top: 10,
  },
  centeredElement: {
    alignItems: "center",
    display: "flex",
    height: "100%",
    justifyContent: "center",
    textAlign: "center",
  },
  clearSearchButton: {
    "&:hover": {
      background: theme.palette.black,
    },
    alignItems: "center",
    background: theme.palette.grey.dark,
    border: 0,
    borderRadius: "50%",
    cursor: "pointer",
    display: "flex",
    height: 16,
    justifyContent: "center",
    padding: theme.spacing(0.5),
    transition: theme.hoverTransition,
    width: 16,
  },
  clearSearchButtonIcon: {
    "& rect": {
      fill: theme.palette.white,
      stroke: theme.palette.white,
      strokeWidth: 2,
    },
  },
  list: {
    "&::-webkit-scrollbar": {
      width: "4px",
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: theme.palette.grey.main,
    },
    "&::-webkit-scrollbar-thumb:hover": {
      backgroundColor: theme.palette.grey.dark,
    },
    height: "100%",
    overflowY: "auto",
  },
  searchIcon: {
    marginRight: theme.spacing(1.25),
  },
  searchInput: {
    border: 0,
    outline: 0,
    padding: [theme.spacing(2), 0],
    width: "100%",
  },
  searchInputContainer: {
    alignItems: "center",
    borderBottom: `1px solid ${theme.palette.grey.light}`,
    display: "flex",
    marginBottom: theme.spacing(2),
    width: "100%",
  },
  tokenBalance: {
    color: theme.palette.black,
  },
  tokenBalanceWrapper: {
    marginLeft: "auto",
  },
  tokenButton: {
    "&:hover": {
      background: theme.palette.grey.main,
    },
    alignItems: "center",
    background: theme.palette.grey.light,
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    justifyContent: "space-between",
    overflow: "hidden",
    padding: theme.spacing(2),
    transition: theme.hoverTransition,
    width: "100%",
  },
  tokenButtonWrapper: {
    "&:not(:first-of-type)": {
      marginTop: theme.spacing(1),
    },
    position: "relative",
  },
  tokenIcon: {
    marginRight: theme.spacing(1),
  },
  tokenInfo: {
    alignItems: "center",
    display: "flex",
  },
  tokenInfoButton: {
    "&:hover": {
      background: theme.palette.grey.main,
    },
    background: "transparent",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    height: 32,
    padding: 8,
    position: "absolute",
    right: theme.spacing(2),
    top: "50%",
    transform: "translateY(-50%)",
    width: 32,
  },
  tokenInfoButtonIcon: {
    "& path": {
      fill: theme.palette.grey.dark,
    },
  },
  tokenInfoWithBalance: {
    alignItems: "center",
    display: "flex",
    marginRight: 48,
  },
  tokenList: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
  },
}));

export const useTokenListRedesignStyles = createUseStyles((theme: Theme) => ({
  addTokenButton: {
    "&:hover": {
      background: theme.palette.primary.main,
      borderColor: theme.palette.primary.main,
      color: theme.palette.white.mainRedesign,
    },
    background: "rgba(65, 201, 171, 0.12)",
    border: "1px solid rgba(65, 201, 171, 0.3)",
    borderRadius: 12,
    color: theme.palette.primary.dark,
    cursor: "pointer",
    flexShrink: 0,
    fontWeight: 600,
    minWidth: 100,
    padding: `${theme.spacing(1.25)}px ${theme.spacing(1.75)}px`,
    transition: "background 160ms ease, border-color 160ms ease, color 160ms ease",
  },
  centeredElement: {
    alignItems: "center",
    color: theme.palette.grey.dark,
    display: "flex",
    flex: 1,
    justifyContent: "center",
    minHeight: 140,
    padding: theme.spacing(3),
    textAlign: "center",
  },
  clearSearchButton: {
    "&:hover:not(:disabled)": {
      background: "rgba(65, 201, 171, 0.12)",
      boxShadow: "none !important",
      transform: "none !important",
    },
    "&:hover:not(:disabled) path, &:hover:not(:disabled) rect": {
      fill: theme.palette.primary.dark,
      stroke: theme.palette.primary.dark,
    },
    alignItems: "center",
    background: "rgba(0, 0, 0, 0.04)",
    border: 0,
    borderRadius: "50%",
    boxShadow: "none !important",
    cursor: "pointer",
    display: "flex",
    flexShrink: 0,
    height: 28,
    justifyContent: "center",
    padding: 0,
    transform: "none !important",
    transition: "background 160ms ease",
    width: 28,
  },
  clearSearchButtonIcon: {
    "& path": {
      fill: theme.palette.grey.dark,
      transition: "fill 160ms ease, stroke 160ms ease",
    },
    "& rect": {
      fill: theme.palette.grey.dark,
      stroke: theme.palette.grey.dark,
      strokeWidth: 2,
      transition: "fill 160ms ease, stroke 160ms ease",
    },
    display: "block",
    height: 11,
    width: 11,
  },
  list: {
    "&::-webkit-scrollbar": {
      width: 4,
    },
    "&::-webkit-scrollbar-thumb": {
      backgroundColor: "rgba(10, 11, 13, 0.18)",
      borderRadius: 999,
    },
    "&::-webkit-scrollbar-thumb:hover": {
      backgroundColor: "rgba(10, 11, 13, 0.32)",
    },
    "&::-webkit-scrollbar-track": {
      backgroundColor: "transparent",
    },
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: theme.spacing(1.25),
    minHeight: 0,
    overflowX: "hidden",
    overflowY: "auto",
    padding: "2px 6px 8px 0",
    [theme.breakpoints.downM]: {
      gap: theme.spacing(1),
      padding: "2px 2px 6px 0",
    },
  },
  searchIcon: {
    flexShrink: 0,
    height: 18,
    marginRight: theme.spacing(1.5),
    opacity: 0.7,
    width: 18,
  },
  searchInput: {
    "&::placeholder": {
      color: theme.palette.grey.dark,
      opacity: 0.85,
    },
    backgroundColor: "transparent",
    border: 0,
    color: theme.palette.black,
    flex: 1,
    fontSize: 15,
    outline: 0,
    padding: `${theme.spacing(1.75)}px 0`,
    width: "100%",
    [theme.breakpoints.downM]: {
      fontSize: 14,
      padding: `${theme.spacing(1)}px 0`,
    },
  },
  searchInputContainer: {
    "&:focus-within": {
      backgroundColor: "#FFFFFF",
      borderColor: "rgba(65, 201, 171, 0.55)",
      boxShadow: "0 0 0 4px rgba(65, 201, 171, 0.12)",
    },
    alignItems: "center",
    backgroundColor: "#F3F6F7",
    border: "1px solid rgba(10, 11, 13, 0.06)",
    borderRadius: 16,
    display: "flex",
    flexShrink: 0,
    marginBottom: theme.spacing(2.5),
    padding: `0 ${theme.spacing(2)}px`,
    transition: "background 160ms ease, border-color 160ms ease, box-shadow 160ms ease",
    width: "100%",
    [theme.breakpoints.downM]: {
      borderRadius: 12,
      marginBottom: theme.spacing(1.25),
      padding: `0 ${theme.spacing(1.5)}px`,
    },
  },
  tokenBalance: {
    color: theme.palette.grey.veryDark,
    fontWeight: 600,
    [theme.breakpoints.downM]: {
      fontSize: 12,
    },
  },
  tokenBalanceWrapper: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    justifyContent: "flex-end",
    marginLeft: "auto",
    minHeight: 20,
    minWidth: 112,
    paddingLeft: theme.spacing(2),
    [theme.breakpoints.downM]: {
      minWidth: 88,
      paddingLeft: theme.spacing(1),
    },
  },
  tokenButton: {
    "&:hover, &:hover:not(:disabled)": {
      background: "transparent",
      boxShadow: "none !important",
      transform: "none !important",
    },
    alignItems: "center",
    background: "transparent",
    border: "none",
    borderRadius: 0,
    boxShadow: "none !important",
    cursor: "pointer",
    display: "flex",
    flex: 1,
    justifyContent: "space-between",
    minWidth: 0,
    padding: 0,
    textAlign: "left",
    transform: "none !important",
    transition: "none",
    width: "100%",
  },
  tokenButtonWrapper: {
    "&:hover": {
      background: "linear-gradient(135deg, rgba(65, 201, 171, 0.16) 0%, rgba(243, 205, 82, 0.1) 100%)",
      boxShadow: "inset 0 0 0 1.5px rgba(65, 201, 171, 0.5)",
    },
    alignItems: "center",
    background: "#F3F6F7",
    borderRadius: 16,
    boxShadow: "inset 0 0 0 1px rgba(10, 11, 13, 0.04)",
    display: "flex",
    flexShrink: 0,
    gap: theme.spacing(1.25),
    padding: `${theme.spacing(1.75)}px ${theme.spacing(2.25)}px`,
    transition: "background 160ms ease, box-shadow 160ms ease",
    width: "100%",
    [theme.breakpoints.downM]: {
      borderRadius: 12,
      gap: theme.spacing(1),
      padding: `${theme.spacing(1.25)}px ${theme.spacing(1.5)}px`,
    },
  },
  tokenIcon: {
    marginRight: theme.spacing(1.25),
  },
  tokenIdentity: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  tokenInfo: {
    alignItems: "center",
    display: "flex",
    minWidth: 0,
  },
  tokenInfoButton: {
    "&:hover path": {
      fill: theme.palette.primary.dark,
    },
    "&:hover, &:hover:not(:disabled)": {
      background: "rgba(65, 201, 171, 0.16)",
      borderColor: "rgba(65, 201, 171, 0.35)",
      boxShadow: "none !important",
      transform: "none !important",
    },
    alignItems: "center",
    background: "rgba(255, 255, 255, 0.85)",
    border: "1px solid rgba(10, 11, 13, 0.05)",
    borderRadius: "50%",
    boxShadow: "none !important",
    cursor: "pointer",
    display: "flex",
    flexShrink: 0,
    height: 32,
    justifyContent: "center",
    lineHeight: 0,
    padding: 0,
    transform: "none !important",
    transition: "background 160ms ease, border-color 160ms ease",
    width: 32,
    [theme.breakpoints.downM]: {
      background: "transparent",
      border: "none",
      height: 22,
      width: 22,
    },
  },
  tokenInfoButtonIcon: {
    "& path": {
      fill: theme.palette.grey.dark,
      transition: "fill 160ms ease",
    },
    display: "block",
    flexShrink: 0,
    height: 16,
    width: 16,
    [theme.breakpoints.downM]: {
      height: 18,
      width: 18,
    },
  },
  tokenInfoWithBalance: {
    alignItems: "center",
    display: "flex",
    gap: theme.spacing(1.5),
    minWidth: 0,
    width: "100%",
  },
  tokenList: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: 0,
    overflow: "visible",
    width: "100%",
  },
  tokenName: {
    color: theme.palette.black,
    fontSize: 15,
    fontWeight: 600,
    letterSpacing: "-0.01em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    [theme.breakpoints.downM]: {
      fontSize: 13,
    },
  },
  tokenSymbol: {
    color: theme.palette.grey.dark,
    fontSize: 12,
    fontWeight: 500,
    letterSpacing: "0.02em",
    lineHeight: "16px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
    [theme.breakpoints.downM]: {
      fontSize: 11,
      lineHeight: "14px",
    },
  },
}));
