import { createUseStyles } from "react-jss";

import { Theme } from "src/styles/theme";

export const useTokenInfoTableStyles = createUseStyles((theme: Theme) => ({
  alignRow: {
    alignItems: "center",
    display: "flex",
    gap: theme.spacing(1),
  },
  button: {
    "&:hover": {
      background: theme.palette.grey.main,
    },
    background: "transparent",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    display: "flex",
    padding: theme.spacing(1),
  },
  chainIcon: {
    height: 20,
    width: 20,
  },
  copyIcon: {
    "& path": {
      fill: theme.palette.grey.dark,
    },
    height: 16,
    width: 16,
  },
  newWindowIcon: {
    "& path": {
      fill: theme.palette.grey.dark,
      stroke: theme.palette.grey.dark,
      strokeWidth: 1,
    },
    height: 16,
    width: 16,
  },
  row: {
    alignItems: "center",
    backgroundColor: "#F7F7F7",
    borderRadius: 12,
    display: "flex",
    flexDirection: "column",
    gap: theme.spacing(0.5),
    justifyContent: "space-between",
    marginBottom: theme.spacing(1),
    padding: theme.spacing(1.5),
    [theme.breakpoints.upSm]: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderRadius: 0,
      flexDirection: "row",
      gap: theme.spacing(1),
      height: 48,
      marginBottom: 0,
      padding: 0,
    },
  },
  rowRightBlock: {
    alignItems: "center",
    display: "flex",
  },
  tokenAddress: {
    alignItems: "center",
    display: "flex",
    gap: theme.spacing(1),
    paddingRight: theme.spacing(1),
  },
  wrapper: {
    background: theme.palette.white,
  },
}));

export const useTokenInfoTableRedesignStyles = createUseStyles((theme: Theme) => ({
  alignRow: {
    alignItems: "center",
    color: theme.palette.grey.dark,
    cursor: "default",
    display: "flex",
    flexShrink: 0,
    fontSize: 13,
    fontWeight: 500,
    gap: theme.spacing(1),
    letterSpacing: "0.01em",
  },
  button: {
    "&:disabled": {
      cursor: "default",
      opacity: 0.4,
    },
    "&:hover:not(:disabled)": {
      background: "rgba(65, 201, 171, 0.16)",
      borderColor: "rgba(65, 201, 171, 0.35)",
      boxShadow: "none !important",
      transform: "none !important",
    },
    "&:hover:not(:disabled) path": {
      fill: theme.palette.primary.dark,
      stroke: theme.palette.primary.dark,
    },
    alignItems: "center",
    background: "#FFFFFF",
    border: "1px solid rgba(10, 11, 13, 0.06)",
    borderRadius: "50%",
    boxShadow: "none !important",
    cursor: "pointer",
    display: "flex",
    flexShrink: 0,
    height: 32,
    justifyContent: "center",
    lineHeight: 0,
    padding: 0,
    textDecoration: "none",
    transform: "none !important",
    transition: "background 160ms ease, border-color 160ms ease",
    width: 32,
    [theme.breakpoints.downM]: {
      height: 28,
      width: 28,
    },
  },
  chainIcon: {
    flexShrink: 0,
    height: 18,
    width: 18,
  },
  copyIcon: {
    "& path": {
      fill: theme.palette.grey.dark,
      transition: "fill 160ms ease",
    },
    display: "block",
    height: 14,
    width: 14,
  },
  newWindowIcon: {
    "& path": {
      fill: theme.palette.grey.dark,
      stroke: theme.palette.grey.dark,
      strokeWidth: 1,
      transition: "fill 160ms ease, stroke 160ms ease",
    },
    display: "block",
    height: 14,
    width: 14,
  },
  row: {
    "&:last-child": {
      borderBottom: "none",
    },
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottom: "1px solid rgba(10, 11, 13, 0.08)",
    borderRadius: 0,
    boxShadow: "none",
    cursor: "default",
    display: "flex",
    flexDirection: "row",
    flexShrink: 0,
    gap: theme.spacing(1.5),
    justifyContent: "space-between",
    minHeight: 52,
    padding: `${theme.spacing(1.5)}px 0`,
    userSelect: "none",
    width: "100%",
    [theme.breakpoints.downM]: {
      alignItems: "flex-start",
      flexDirection: "column",
      gap: theme.spacing(0.75),
      minHeight: 0,
      padding: `${theme.spacing(1.25)}px 0`,
    },
  },
  rowRightBlock: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: theme.spacing(0.75),
    minWidth: 0,
  },
  tokenAddress: {
    color: theme.palette.black,
    cursor: "default",
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: "-0.01em",
    overflow: "hidden",
    paddingRight: 0,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    [theme.breakpoints.downM]: {
      fontSize: 13,
    },
  },
  value: {
    color: theme.palette.black,
    cursor: "default",
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: "-0.01em",
    overflow: "hidden",
    textAlign: "right",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    [theme.breakpoints.downM]: {
      fontSize: 13,
      textAlign: "left",
    },
  },
  wrapper: {
    backgroundColor: "#F3F6F7",
    borderRadius: 16,
    boxShadow: "inset 0 0 0 1px rgba(10, 11, 13, 0.04)",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: 0,
    overflow: "hidden",
    padding: `${theme.spacing(0.5)}px ${theme.spacing(2.25)}px`,
    width: "100%",
    [theme.breakpoints.downM]: {
      borderRadius: 12,
      padding: `${theme.spacing(0.25)}px ${theme.spacing(1.5)}px`,
    },
  },
}));
