import { createUseStyles } from "react-jss";

import { Theme } from "src/styles/theme";

export const useSnackbarStyles = createUseStyles((theme: Theme) => ({
  "@keyframes errorDialogIn": {
    from: { opacity: 0, transform: "translateY(8px) scale(0.97)" },
    to: { opacity: 1, transform: "translateY(0) scale(1)" },
  },
  closeButton: {
    "&:hover": {
      background: theme.palette.grey.main,
    },
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    marginLeft: theme.spacing(2.5),
    padding: theme.spacing(0.75),
    transition: theme.hoverTransition,
  },
  closeIcon: {
    "& rect": {
      fill: theme.palette.grey.dark,
    },
    alignItems: "center",
    display: "flex",
    height: 16,
    justifyContent: "center",
    width: 16,
  },
  errorActions: {
    display: "flex",
    gap: theme.spacing(1.5),
    justifyContent: "center",
    marginTop: theme.spacing(3),
    width: "100%",
  },
  errorBackdrop: {
    alignItems: "center",
    backdropFilter: "blur(2px)",
    background: "rgba(0, 0, 0, 0.35)",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    padding: theme.spacing(2),
    position: "fixed",
    zIndex: 9999,
  },
  errorCloseButton: {
    "&:hover": {
      background: theme.palette.grey.main,
    },
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    padding: theme.spacing(0.75),
    position: "absolute",
    right: theme.spacing(1.5),
    top: theme.spacing(1.5),
    transition: theme.hoverTransition,
  },
  errorDialog: {
    alignItems: "center",
    animation: "$errorDialogIn 180ms ease-out",
    background: theme.palette.white.mainRedesign,
    borderRadius: 20,
    boxShadow: `0 16px 48px rgba(0, 0, 0, 0.18), 0 0 0 1px rgba(232, 67, 13, 0.15)`,
    display: "flex",
    flexDirection: "column",
    maxHeight: "80vh",
    maxWidth: 480,
    overflowY: "auto",
    padding: [theme.spacing(4), theme.spacing(3), theme.spacing(3)],
    position: "relative",
    textAlign: "center",
    width: "100%",
  },
  errorIcon: {
    height: 48,
    marginBottom: theme.spacing(2),
    width: 48,
  },
  errorPrimaryButton: {
    "&:hover": {
      backgroundColor: theme.palette.primary.dark,
    },
    backgroundColor: theme.palette.primary.main,
    border: 0,
    borderRadius: 12,
    color: theme.palette.white.main,
    cursor: "pointer",
    flex: 1,
    fontSize: 16,
    fontWeight: 600,
    maxWidth: 200,
    padding: [theme.spacing(1.5), theme.spacing(3)],
    transition: theme.hoverTransition,
  },
  errorSecondaryButton: {
    "&:hover": {
      background: theme.palette.grey.main,
    },
    backgroundColor: "transparent",
    border: `1px solid ${theme.palette.grey.main}`,
    borderRadius: 12,
    color: theme.palette.black,
    cursor: "pointer",
    flex: 1,
    fontSize: 16,
    fontWeight: 600,
    maxWidth: 200,
    padding: [theme.spacing(1.5), theme.spacing(3)],
    transition: theme.hoverTransition,
  },
  errorText: {
    color: theme.palette.grey.dark,
    fontSize: 16,
    lineHeight: "24px",
    margin: 0,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  errorTitle: {
    color: theme.palette.black,
    fontSize: 20,
    fontWeight: 700,
    lineHeight: "28px",
    margin: [0, 0, theme.spacing(1)],
  },
  message: {
    color: theme.palette.black,
    flex: 1,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: "20px",
    margin: [0, theme.spacing(1.5)],
    whiteSpace: "pre-wrap",
  },
  messageIcon: {
    height: 24,
    width: 24,
  },
  reportButton: {
    "&:hover": {
      backgroundColor: theme.palette.primary.dark,
    },
    backgroundColor: theme.palette.primary.main,
    border: 0,
    borderRadius: 12,
    color: theme.palette.white.main,
    cursor: "pointer",
    fontWeight: 600,
    padding: `${theme.spacing(0.5)}px ${theme.spacing(2)}px`,
    transition: theme.hoverTransition,
  },
  root: {
    bottom: theme.spacing(2),
    left: 0,
    position: "fixed",
    right: 0,
    width: "100%",
    zIndex: 9999,
  },
  wrapper: {
    alignItems: "center",
    background: theme.palette.white.mainRedesign,
    borderRadius: 16,
    display: "flex",
    justifyContent: "space-between",
    margin: "0 auto",
    maxWidth: "400px",
    padding: `${theme.spacing(1.5)}px ${theme.spacing(2)}px`,
    width: "90%",
  },
  wrapperError: {
    boxShadow: `0 8px 32px ${theme.palette.error.light}, 0 0 0 1px rgba(232, 67, 13, 0.15)`,
  },
  wrapperSuccess: {
    boxShadow: `0 8px 32px rgba(65, 201, 171, 0.25), 0 0 0 1px rgba(65, 201, 171, 0.2)`,
  },
}));
