import { createUseStyles } from "react-jss";

import { Theme } from "src/styles/theme";

export const useTokenSelectorHeaderStyles = createUseStyles((theme: Theme) => ({
  backButton: {
    "&:hover": {
      background: theme.palette.grey.main,
    },
    alignItems: "center",
    background: theme.palette.grey.light,
    border: 0,
    borderRadius: "50%",
    cursor: "pointer",
    display: "flex",
    height: theme.spacing(4),
    justifyContent: "center",
    left: 0,
    padding: 0,
    position: "absolute",
    transition: theme.hoverTransition,
    width: theme.spacing(4),
  },
  backButtonIcon: {
    height: 16,
    width: 16,
  },
  closeButton: {
    "&:hover": {
      background: theme.palette.grey.main,
    },
    alignItems: "center",
    background: theme.palette.grey.light,
    border: 0,
    borderRadius: "50%",
    cursor: "pointer",
    display: "flex",
    height: theme.spacing(4),
    justifyContent: "center",
    padding: 0,
    position: "absolute",
    right: 0,
    transition: theme.hoverTransition,
    width: theme.spacing(4),
  },
  closeButtonIcon: {
    height: 16,
    width: 16,
  },
  tokenSelectorHeader: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
    marginBottom: theme.spacing(1),
    padding: [theme.spacing(0.5), 0],
    position: "relative",
  },
}));

export const useTokenSelectorHeaderRedesignStyles = createUseStyles((theme: Theme) => ({
  backButton: {
    "&:hover:not(:disabled)": {
      background: "rgba(65, 201, 171, 0.14)",
      boxShadow: "none !important",
      transform: "none !important",
    },
    "&:hover:not(:disabled) path": {
      fill: theme.palette.primary.dark,
      stroke: theme.palette.primary.dark,
    },
    alignItems: "center",
    background: "#F3F6F7",
    border: 0,
    borderRadius: "50%",
    bottom: 0,
    boxShadow: "none !important",
    cursor: "pointer",
    display: "flex",
    height: 40,
    justifyContent: "center",
    left: 0,
    margin: "auto 0",
    padding: 0,
    position: "absolute",
    top: 0,
    transform: "none !important",
    transition: "background 160ms ease",
    width: 40,
  },
  backButtonIcon: {
    display: "block",
    height: 16,
    transition: "fill 160ms ease, stroke 160ms ease",
    width: 16,
  },
  closeButton: {
    "&:hover:not(:disabled)": {
      background: "rgba(65, 201, 171, 0.14)",
      boxShadow: "none !important",
      transform: "none !important",
    },
    "&:hover:not(:disabled) path, &:hover:not(:disabled) rect": {
      fill: theme.palette.primary.dark,
    },
    alignItems: "center",
    background: "#F3F6F7",
    border: 0,
    borderRadius: "50%",
    bottom: 0,
    boxShadow: "none !important",
    cursor: "pointer",
    display: "flex",
    height: 40,
    justifyContent: "center",
    margin: "auto 0",
    padding: 0,
    position: "absolute",
    right: 0,
    top: 0,
    transform: "none !important",
    transition: "background 160ms ease",
    width: 40,
    [theme.breakpoints.downM]: {
      height: 34,
      width: 34,
    },
  },
  closeButtonIcon: {
    display: "block",
    height: 14,
    transition: "fill 160ms ease",
    width: 14,
  },
  title: {
    color: theme.palette.black,
    fontSize: 22,
    fontWeight: 700,
    letterSpacing: "-0.02em",
    [theme.breakpoints.downM]: {
      fontSize: 18,
    },
  },
  tokenSelectorHeader: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    justifyContent: "center",
    marginBottom: theme.spacing(2.5),
    minHeight: 44,
    overflow: "visible",
    padding: `${theme.spacing(0.5)}px 0`,
    position: "relative",
    [theme.breakpoints.downM]: {
      marginBottom: theme.spacing(1.25),
      minHeight: 38,
    },
  },
}));
